### ISSUE TITLE
The credential you entered was not authorized. Please double-check and try again

### ISSUE THREAD

**Issue by projekt86** [kobiton/bitrise-step-kobiton-upload-apps-repo#7]
I had `The credential you entered was not authorized. Please double-check and try again` error response. 
There is hardcoded api-test domain `https://api-test.kobiton.com/v1/apps/uploadUrl`, should not be `https://api.kobiton.com/v1/apps/uploadUrl` ?

**Comment by Nhattd97** [comment]
Hi @projekt86 , thanks for submitting the issue. It's should be fixed in version `1.0.2`
